# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - feature/azure-function-app

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'AzureResourceDeployment'
    jobs:
    - job: 'AzureResourceDeployment'
      displayName: 'Azure Resource Deployment'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'vimtipsdaily-sc'
          subscriptionId: 'b8645259-b8c5-4a31-a9f5-da30f2929e05'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'vimtipsdaily-rg'
          location: 'South Central US'
          templateLocation: 'Linked artifact'
          csmFile: './arm/template.json'
          csmParametersFile: './arm/parameters.json'
          deploymentMode: 'Incremental'

  - stage: build
    jobs:
    - job: 'Build'
      displayName: 'Build'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - script: npm install
        displayName: 'npm install and build'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: '$(System.ArtifactsDirectory)'

  - stage: prod
    dependsOn: build
    jobs:
    - deployment: deployProd
      displayName: 'Deploy to Prod'
      environment: vimtipsdaily-env
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@1
              inputs:
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: AzureFunctionApp@1
              inputs:
                azureSubscription:  'vimtipsdaily-sc'
                appType: functionApp
                appName: vimtipsdaily
                package: '$(System.DefaultWorkingDirectory)/**/*.zip'
