# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - feature/azure-function-app

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'AzureResourceDeployment'
    jobs:
    - job: 'AzureResourceDeployment'
      displayName: 'Azure Resource Deployment'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'vimtipsdaily-sc'
          subscriptionId: 'b8645259-b8c5-4a31-a9f5-da30f2929e05'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'vimtipsdaily-rg'
          location: 'South Central US'
          templateLocation: 'Linked artifact'
          csmFile: './arm/template.json'
          csmParametersFile: './arm/parameters.json'
          deploymentMode: 'Incremental'

  - stage: 'Build'
    jobs:
    - job: 'Build'
      displayName: 'Build'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'
